package com.ingramcontent.dataverse;

import com.ingramcontent.dataverse.model.Signal;
import com.ingramcontent.dataverse.model.Xformer;

rule "Item Load Pipeline"
    ruleflow-group 'pipelineCodeRule'
	when 
		signal: Signal("ItemLoad".equalsIgnoreCase(pipelineCode) 
		        && totalRecord != null 
		        && totalRecord.size() > 0
		        && totalRecord.get(0) > 7000);
		xformer: Xformer();
	then
		xformer.setIsInitialLoad(true);
	end
	
rule "Publisher Load Pipeline"
    ruleflow-group 'pipelineCodeRule'
	when 
		signal: Signal("PublisherLoad".equalsIgnoreCase(pipelineCode) 
		        && totalRecord != null 
		        && totalRecord.size() > 0
		        && totalRecord.get(0) > 5000);
		xformer: Xformer();
	then
		xformer.setIsInitialLoad(true);
	end	