package com.ingramcontent.dataverse.handler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RESTWorkItemHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RESTWorkItemHandler() {
    }




}