package com.ingramcontent.dataverse.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MessageRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MessageRequest() {
    }




}